### ISSUE TITLE
Add seed file

### ISSUE THREAD

**Issue by thorgriffs** [thorgriffs/make-your-madlibs#20]

**Comment by thorgriffs** [comment]
Add templates with blank words placeholders to the templates table:

**Here are some templates:**
https://www.pinterest.com/pin/809662839234751294/?d=t&mt=login

https://www.pinterest.com/pin/239746380150460227/?d=t&mt=login

https://www.pinterest.com/pin/761882461951797424/?d=t&mt=login

https://www.pinterest.com/pin/4292562133064018/?d=t&mt=login

**Here is the parser documentation to reference the formatting:**
https://www.npmjs.com/package/madlibs-template-parser

**Comment by mmeii** [comment]
added test seed file for migration, success
