### ISSUE TITLE
Find stories

### ISSUE THREAD

**Issue by mmeii** [thorgriffs/make-your-madlibs#25]
find madlib story templates - 3 to start with

**Comment by thorgriffs** [comment]
https://www.pinterest.com/pin/809662839234751294/?d=t&mt=login

https://www.pinterest.com/pin/239746380150460227/?d=t&mt=login

https://www.pinterest.com/pin/761882461951797424/?d=t&mt=login

https://www.pinterest.com/pin/4292562133064018/?d=t&mt=login
